name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - flask
  - flask-restful
  - gdal
  - geopandas
  - lxml
  - requests
  - pandas
  - python=3.6.5
  - python-dotenv
  - xarray
  - numpy
  - scipy
  - polyline
  - pip:
    - schedule
