openapi: 3.0.0
info:
  title: Community Snow Observations API
  description: API for retrieving community-generated snow depth observations
  version: 0.0.1

servers:
  - url: localhost:5000
    description: Local development server

paths:
  /obs:
    get:
      summary: Returns a list of snow depth observations
      parameters:
        - name: limit
          in: query
          description: Maximum number of records to return
          schema:
            type: integer
            format: int64
            minimum: 1
            default: 1000
        - name: page
          in: query
          description: Page number of results
          schema:
            type: integer
            format: int64
            minimum: 1
            default: 1
        - name: start
          in: query
          description: Earliest unix timestamp (in milliseconds) of results
          schema:
            type: integer
            format: int64
            minimum: 1427458000000
            default: 1427458000000
        - name: end
          in: query
          description: Latest unix timestamp (in milliseconds) of results
          schema:
            type: integer
            format: int64
            minimum: 1427458000000
            default: Present time
        - name: region
          in: query
          description: Region to return results from. Can be specified as a series of coordinates separated by `|`, e.g. `<lat_1>,<long_1>|<lat_2>,<long_2>|<lat_3>,<long_3>` or as an [encoded polyline](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)
          schema:
            type: string
            default: Empty string
      responses:
        '200':
          description: A JSON array of observations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CSO_Observation'
  /snodas:
    get:
      summary: Returns a timeseries of snow depth estimations sourced from SNODAS
      parameters:
        - name: lat
          in: query
          description: Latitude of results
          required: true
          schema:
            type: number
            format: float
        - name: long
          in: query
          description: Longitude of results
          required: true
          schema:
            type: number
            format: float
      responses:
        '200':
          description: A JSON array of SNODAS Estimations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SNODAS_Estimation'
components:
  schemas:
    SNODAS_Estimation:
      type: object:
      properties:
        snow_depth:
          type: number
          format: float
          example: 28.799999237060547
        timestamp:
          type: integer
          format: int64
          example: 1514764800
    CSO_Observation:
      type: object
      properties:
        author_name:
          type: string
          example: Jessica Smith
        id:
          type: string
          example: 48f9481dbcaef8g12dhd8482
        timestamp:
          type: integer
          format: int64
          example: 1500000000000
        lat:
          type: number
          format: float
          example: 48.5412
        long:
          type: number
          format: float
          example: 21.7530
        type:
          type: string
          example: snow_conditions
        snow_depth:
          type: number
          format: float
          example: 15.63
        elevation:
          type: number
          format: float
          example: 184.52
